### ISSUE TITLE
sonar-config: allow customisation of log location

### ISSUE THREAD

**Issue by dhutchison** [okorach/sonar-tools#1099]
Hi,

As part of trying to automate our Configuration-as-Code for Sonarqube we were trying to integrate calling this library as part of a python lambda function we use for some other configuration aspects. All was going well until we tried running this deployed, and got this error:

```
[ERROR] OSError: [Errno 30] Read-only file system: '/var/task/sonar-tools.log'
```
From looking through the code it appears this logging is always enabled and the location cannot be customised. 

I also noticed that there is some functionality which calls exit in the event of certain types of error - it would be nice if this could be optional / configurable for if this is being consumed as a library, but that is probably . 

This probably wasn't an expected use case as it took a little bit of inspecting the code to work out, although I did wonder if it fed in to the intention for #641. 

I'm happy to contribute some code for this scenario, but wanted to put them in an issue for any discussion before doing so. 

For the log location I think allowing a configuration setting to be passed in for the log output file (defaulting to current location) would be beneficial. 

What do you think?

Thanks.

**Comment by okorach** [comment]
Hi @dhutchison,

Happy to read that sonar-config might be of some use to the community, and thanks for the suggestion, I understand the use case and I also can tell this was not thought initially.
I would gladly accept PRs if you feel this contributing. Fixing the logging config is probably not difficult to do.
The second part, doing something better that exis (yes I know that's dirty), is probably a bit more time consuming and I only have the time of my free time... that is not exclusively allocated to sonar-tools :-)

**Comment by dhutchison** [comment]
Oh I know the feeling well. My OSS  and generally tinkering list far exceeds the time life allows 😀 

I'll pull together something later in the week for the logging piece, and make another issue with ideas for the exit piece once some inspiration strikes.

**Comment by okorach** [comment]
Hi @dhutchison,
I fixed this logging thing since it was really easy. You can have a preview by building yourself and installing locally the `sonar_tools-3.1-py3-none-any.whl` file.
```
# Get the code
git clone https://github.com/okorach/sonar-tools.git
cd sonar-tools
# Install build dependencies
pip install -f requirements-to-build.txt
# Build
python3 setup.py bdist_wheel
# Install locally built package
pip install dist/sonar_tools-3.1-py3-none-any.whl
```
