### ISSUE TITLE
SARIF format incorrect (findings export)

### ISSUE THREAD

**Issue by FWest98** [okorach/sonar-tools#1173]
On the latest iteration of `master`, the SARIF-formatted output seems to be broken. In particular, what used to be the contents of the `properties` field, is now the top-level content of the SARIF entry. This did work a few days ago on commit hash https://github.com/okorach/sonar-tools/commit/3ae0843af08a04b492e6ae0899dd310320ac21af

This is the diff (on the left is the old correct version, on the right is the new incorrect version):
![image](https://github.com/okorach/sonar-tools/assets/1918658/84ab47d2-5c1a-4ce7-98aa-f0ceb74fc0c9)

**Comment by okorach** [comment]
Hi @FWest98 ,
Thanks for reporting this.
I'll fix in release 3.2 that should be out pretty soon
