### ISSUE TITLE
sonar-autit: despite options -f or -l output is displayed to stdout ( console )

### ISSUE THREAD

**Issue by kad-meedel** [okorach/sonar-tools#1421]
The sonar-audit --help indicates the following:

-l LOGFILE, --logfile LOGFILE
                        Define location of logfile, logs are only sent to stderr if not set

-f FILE, --file FILE Report file, stdout by default

I have used both options, but the output is also routed to the console ( stdout )

It is not a hot issue, but may not have been the intention. 
The logfiles are created correctly. 

I used the latest version: 3.5

Regards,

Bert

**Comment by okorach** [comment]
Hello @kad-meedel ,

First to eliminate eambiguity, the option that defines the output log file is `-l`. `-f` is the output file for whatever `sonar-tools` command you use

Now, the behavior that you describe is the intended one:
- If you don't specify `-l`, logs are sent to stdout
- If you do specify `-l` logs are sent to the given logfile AND stdout

Is there any reason why this behavior would be inconvenient?

**Comment by kad-meedel** [comment]
Hi Olivier,

The options are not inconvenient.

Then I won't fully understand the explanation.
If I give the -l option I would have expected that all output would be written to the log file in the background and **no longer** to the console.

regards,

Bert

**Comment by okorach** [comment]
Hi bert,
That's typically how logging works in a majority of console applications (logging is always sent to stderr, then on top you may send to a log file) so I just followed the general behavior.
If you don't want the stderr logging you may redirect stderr into `/dev/null` (on *Nix systems)

`sonar-audit -f audit.csv 2>/dev/null`
