### ISSUE TITLE
`ratingsAsNumbers` not implemented?

### ISSUE THREAD

**Issue by renefritze** [okorach/sonar-tools#1502]
I'm using sonar-tools 3.6 trying to export some measures. 
``--ratingsAsNumbers`` seems to have no effect for me. Neither with csv nor json output.

AFAICT the option's intention is stored, but never read from again:
https://github.com/search?q=repo%3Aokorach%2Fsonar-tools+CONVERT_OPTIONS&type=code
If that's true, then  `--percentsAsString` and `--datesWithoutTime` would also not work.

**Comment by okorach** [comment]
Hello @renefritze,

Thanks for reporting this. It's supposed to be implemented but, indeed I confirm, it does not work. I'll fix that in next release and add a test to ensure no regression in the future
