### ISSUE TITLE
Group not found

### ISSUE THREAD

**Issue by k0mand1r** [okorach/sonar-tools#1527]
Hi @okorach,

**Environment**:
- SonarQube 10.4
- nginx reverse proxy 
- Sonar-tools 3.7 (also tested earlier version up to 3.2)
- virtualenv
- Python3.11

**Issue**:
We've run into a sudden issue with the creation of groups. We're getting 'Error code 5: Group X not found.' when trying to create a group. By my knowledge the issue seems to be in the flow in groups.py and the get_object().

1. Check if a group exists. If not, create it, otherwise update it. (using groups.exists())
2. groups.exists() return the result of 'get_object()'
3. In get_object() the Group.CACHE does not seem to get filled while it is being used to return a result if a group exists.
```
    o = Group.CACHE.get(name, endpoint.url)
    if not o:
        get_list(endpoint)
    o = Group.CACHE.get(name, endpoint.url)
    if not o:
        raise exceptions.ObjectNotFound(name, message=f"Group '{name}' not found")
    return o
```
4. get_list(endpoint) is not assigned to a variable or the CACHE.
5. get_list(endpoint) only returns 50 items, while search_objects() does allow to pass additional params for the API like pageSize. it's not possible to pass params through get_list() or groups.exists(). So we don't have control over the pageSize and the default only serves a portion of the groups.
6. Adding the results from get_list() to Group.CACHE.put() only returns and fills 50 items in the cache instead of the pageSize. This raises the exception for groups outside the first 50 items. See next screenshot in comment that ps=500 and p=1 is being defined in command line.
```
    for x in get_list(endpoint): 
        Group.CACHE.put(x)
```

What am I missing in how the cache works, how the creation of groups is done in sonar-tools 3.7 or is there a bug with filling the Group.CACHE? 

Similar to [this issue](https://github.com/okorach/sonar-tools/issues/1509) but with groups.

**Comment by k0mand1r** [comment]
<img width="1008" alt="Screenshot 2024-12-06 at 16 39 21" src="https://github.com/user-attachments/assets/22b21b37-8b4d-410c-8cbc-e87c763cc3de">

**Comment by k0mand1r** [comment]
Going by the DEBUG output. The params passed to the search function should include the pageSize=500 and pageIndex=1.
<img width="1456" alt="Screenshot 2024-12-06 at 17 34 54" src="https://github.com/user-attachments/assets/19521ef4-9bae-4312-94a6-6f17b0a6f1aa">

**Comment by okorach** [comment]
Hi @k0mand1r,

Thanks for reporting the problem.
With what tool (is this `sonar-config` ?) and what CLI options do you get this problem?

**Comment by k0mand1r** [comment]
Hi @okorach,
We're using our own python script which imports sonar-tools. In our script we're using the different sonar-tools functions as much as possible.

For example in the screenshot above with the stacktrace:

- create_project.py, create_group and generate_members_groupname are functions in our script. 
- if not groups.exists() (and subsequently get_object() is from sonar-tools (groups.py))

**Comment by k0mand1r** [comment]
> Hi @k0mand1r,
> 
> Thanks for reporting the problem. With what tool (is this `sonar-config` ?) and what CLI options do you get this problem?

Is the intended way to modify SonarQube with sonar-tools?

**Comment by okorach** [comment]
Hello @k0mand1r ,

I understand that actually you use the python API directly?
That's all OK although that was not intended for now (the coupling between the `sonar-tools` and the APIs is a bit to tight for the moment).
Although exposing clean APIs has been my intention for a while see #641.
That said, for the short term I will fix your specific problem. I have already been exposed to the problem of changes between API v1 and v2. I can handle the different page size parameter
