### ISSUE TITLE
Wrong / too old scanner versions

### ISSUE THREAD

**Issue by sylvain-combe-sonarsource** [okorach/sonar-tools#727]
SonarQube scanner versions are usually for bug fixes and improvements that go unnoticed by all projects.
However, some projects might be on a version so old that an upgrade would become mandatory, for the following reasons:
- Security
- Java version compatibility
- SonarQube API changes breaking backward scanner compatibility
For that reason, it would be great for administrators to spot the projects that remained on a too old version of the scanner.

As I see it, such sonar-audit version could require as parameter a minimal version for the different scanners.

Then all projects analysis tasks contexts could be parsed to spot the issue.

**Comment by sylvain-combe-sonarsource** [comment]
wdyt @okorach ?

**Comment by okorach** [comment]
Good idea - Let's see how we can implement that...
