### ISSUE TITLE
Can't export projects on Community 9.0.1

### ISSUE THREAD

**Issue by eucariop** [okorach/sonar-tools#809]
sonar-projects-export -u $SONAR_HOST_URL -t $SONAR_TOKEN >exported_projects.csv
2022-07-04 15:21:43,532 | sonar-tools | INFO    | Set debug level to INFO
2022-07-04 15:21:44,831 | sonar-tools | CRITICAL | Can't export projects on Community and Developer Edition before 9.2, aborting...
FATAL: Can't export projects on Community and Developer Edition before 9.2, aborting...

**Comment by okorach** [comment]
Hello @eucariop,
The behaviour you notice is normal. Project export only became allowed in Community and Developer Edition starting from SonarQube 9.2. So you cannot export projects on a community edition below 9.2.

**Comment by eucariop** [comment]
yes I understand but I'm still looking for how to export and import from 9.0 to 9.2+ without losing data/information
do you know any information?
