### ISSUE TITLE
sonar-loc uses only 500 projects in version 2.4

### ISSUE THREAD

**Issue by HediM1** [okorach/sonar-tools#849]
Hi, I installed version 2.4. With this version I get only 500 projects. With version 1.14 I get all projects. please have a look to the attachment. Ciao Hed
![housekeeper](https://user-images.githubusercontent.com/110611539/182854609-fcf1e2ef-efed-4775-bdac-619ed330dbb5.PNG)
i

**Comment by okorach** [comment]
Thanks for the report @HediM1 . I confirm the problem. This will be fixed in v2.5

**Comment by okorach** [comment]
@HediM1 the problem was not only limited to sonar-loc. It impacted mostly all sonar-tools so I released quickly a patch release. This is fixed in v2.4.1 - See https://github.com/okorach/sonar-tools/releases/tag/v2.4.1

**Comment by HediM1** [comment]
Thank you for the fast processing.

Before I install the new version and test it ……
I got another problem:

Our developers are working with Jira – Bitbucket – Jenkins – Sonar ….
So branches in Bitbucket are created via Jira-tasks and so we got a branch inside Sonar with this name - 
![branch-problem](https://user-images.githubusercontent.com/110611539/184819349-f1dd85cb-a08e-4074-a24d-a4ff209004fa.PNG)


 please have a look to the attached file.

Hopefully you can see that the ‘-‘ are different (between PJ522716 and 545626 and between e.g. ACE and internet)

The URL is this: https://......./dashboard?branch=feature%2FPJ522716%E2%80%93545626-ACE-internetb_10&id=EB2_eb2-it_javaweb

and it works.

But the API-Call – done via your tool (version 1.14) – doesn’t work.

10.110.133.166 | 10.182.242.4 "tuson003" 10.111.96.97 9000 11/Aug/2022:08:26:22 +0200 | "GET /api/measures/component?component=EB2_eb2-it_javaweb&metricKeys=ncloc&branch=feature%2FPJ522716%C3%A2%E2%82%AC%E2%80%9C545626-ACE-internetb_10 HTTP/1.1" | "sonar.intranet.unicreditgroup.eu" | 404 143 6 | "-" | "python-requests/2.19.1" | "-" | remoteLogname:"-" | bytesReceived:"http-nio-0.0.0.0-9000-exec-7"

and the job is interrupted.  
If the problem can’t be solved, for me it would be enough if the job would omit this api-call and would continue working.
