### ISSUE TITLE
 sonar-tools stuck when executing to pull reports from SonarQube community edition 9.7

### ISSUE THREAD

**Issue by prasad-clouduser** [okorach/sonar-tools#854]
Tried to pull the reports with sonarqube admin token using sonar-tools but it stuck during execution and taking forever. I am trying to pull the reports from the latest edition of SonarQube 9.7 community edition, below are the logs. 
```
pip install sonar-tools
Collecting sonar-tools
Downloading sonar_tools-2.4.1-py3-none-any.whl (184 kB)
Collecting datetime
Downloading DateTime-4.7-py2.py3-none-any.whl (52 kB)
Collecting argparse
Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting pytz
Downloading pytz-2022.5-py2.py3-none-any.whl (500 kB)
Collecting python-dateutil
Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting jprops
Downloading jprops-2.0.2-py2.py3-none-any.whl (9.1 kB)
Collecting requests
Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting zope.interface
Downloading zope.interface-5.5.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (253 kB)
Collecting six>=1.5
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting charset-normalizer~=2.0.0
Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting urllib3<1.27,>=1.21.1
Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
Downloading idna-3.4-py3-none-any.whl (61 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from zope.interface->datetime->sonar-tools) (57.5.0)
Installing collected packages: zope.interface, urllib3, six, pytz, idna, charset-normalizer, certifi, requests, python-dateutil, jprops, datetime, argparse, sonar-tools
Successfully installed argparse-1.4.0 certifi-2022.9.24 charset-normalizer-2.0.12 datetime-4.7 idna-3.4 jprops-2.0.2 python-dateutil-2.8.2 pytz-2022.5 requests-2.27.1 six-1.16.0 sonar-tools-2.4.1 urllib3-1.26.12 zope.interface-5.5.0
WARNING: Running pip as the ‘root’ user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: [12. Virtual Environments and Packages — Python 3.11.0 documentation](https://pip.pypa.io/warnings/venv)
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the ‘/usr/local/bin/python -m pip install --upgrade pip’ command.
[Pipeline] sh
Warning: A secret was passed to “sh” using Groovy String interpolation, which is insecure.
Affected argument(s) used the following variable(s): [TOKEN]
See https://jenkins.io/redirect/groovy-string-interpolation for details.
export SONAR_HOST_URL=https://<<Sonar-Host>>.biz
export SONAR_TOKEN=****
sonar-findings-export -t **** -k services --format json
2022-10-27 13:49:44,814 | sonar-tools | INFO | MainThread | Set debug level to INFO
2022-10-27 13:49:44,814 | sonar-tools | INFO | MainThread | sonar-tools version 2.4.1
2022-10-27 13:49:44,815 | sonar-tools | INFO | MainThread | Listing projects
2022-10-27 13:49:45,008 | sonar-tools | INFO | MainThread | Exporting findings for 1 projects with params {‘url’: ‘https://<>>.biz’, ‘projectKeys’: ‘services’, ‘format’: ‘json’, ‘csvSeparator’: ‘,’, ‘threads’: 8, ‘useFindings’: False, ‘withURL’: False}
2022-10-27 13:49:45,008 | sonar-tools | INFO | MainThread | Dumping report to stdout
2022-10-27 13:49:45,008 | sonar-tools | INFO | findingSearch0 | Project ‘services’ issue search
2022-10-27 13:49:45,011 | sonar-tools | INFO | MainThread | Starting finding writer thread ‘findingWriter’
```
It is not going further from here and had to kill it to stop this job.  pls help me

**Comment by okorach** [comment]
Hello @prasad-clouduser,

Difficult to tell what is the problem for now. I will need you do to a few tests:
A few questions:
- Did it work with previous versions of SonarQube ? (like 9.6 for instance)
- Can you run `sonar-findings-export` with option `-v DEBUG` to get more insights on what is your problem ?
- Can you also try to run with only 1 thread, so all in all run:
`sonar-findings-export -v DEBUG --threads 1`

Then send me the output.

Olivier

**Comment by prasad-clouduser** [comment]
Hi @okorach, 

Previously I tested with SonarQube 9.2.3 community edition available on DockerHub and it worked well with that. But we created a custom image with SonarQube with latest version of binary 9.7 version, it is up and running and tried to pull the reports from it, but stuck in the below stage. 

+ pip install sonar-tools
Collecting sonar-tools
  Downloading sonar_tools-2.5-py3-none-any.whl (204 kB)
Collecting datetime
  Downloading DateTime-4.7-py2.py3-none-any.whl (52 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting jprops
  Downloading jprops-2.0.2-py2.py3-none-any.whl (9.1 kB)
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting pytz
  Downloading pytz-2022.5-py2.py3-none-any.whl (500 kB)
Collecting zope.interface
  Downloading zope.interface-5.5.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (253 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from zope.interface->datetime->sonar-tools) (57.5.0)
Installing collected packages: zope.interface, urllib3, six, pytz, idna, charset-normalizer, certifi, requests, python-dateutil, jprops, datetime, argparse, sonar-tools
Successfully installed argparse-1.4.0 certifi-2022.9.24 charset-normalizer-2.0.12 datetime-4.7 idna-3.4 jprops-2.0.2 python-dateutil-2.8.2 pytz-2022.5 requests-2.27.1 six-1.16.0 sonar-tools-2.5 urllib3-1.26.12 zope.interface-5.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[Pipeline] sh
Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.
		 Affected argument(s) used the following variable(s): [TOKEN]
		 See https://jenkins.io/redirect/groovy-string-interpolation for details.
+ export SONAR_HOST_URL=https://sonarhost.biz
+ export SONAR_TOKEN=****
**+ sonar-findings-export -t **** -k services -v DEBUG --threads 1 --format json**
2022-10-31 08:08:18,767 | sonar-tools | INFO    | MainThread      | Set debug level to DEBUG
2022-10-31 08:08:18,768 | sonar-tools | INFO    | MainThread      | sonar-tools version 2.5
2022-10-31 08:08:18,768 | sonar-tools | DEBUG   | MainThread      | GET: squ_ca***08@https://sonarhost.biz/api/projects/search?projects=services
2022-10-31 08:08:18,826 | sonar-tools | DEBUG   | MainThread      | Created object project 'services'
2022-10-31 08:08:18,845 | sonar-tools | INFO    | MainThread      | Exporting findings for 1 projects with params {'url': 'https://sonarhost.biz', 'projectKeys': 'services', 'format': 'json', 'csvSeparator': ',', 'threads': 1, 'useFindings': False, 'withURL': False}
2022-10-31 08:08:18,845 | sonar-tools | INFO    | MainThread      | Dumping report to stdout
2022-10-31 08:08:18,845 | sonar-tools | DEBUG   | MainThread      | Writing to stdout
2022-10-31 08:08:18,846 | sonar-tools | DEBUG   | MainThread      | Queue <queue.Queue object at 0x7fc3b4fdfc50> task services put
2022-10-31 08:08:18,846 | sonar-tools | DEBUG   | MainThread      | Starting finding search thread 'findingSearch0'
2022-10-31 08:08:18,846 | sonar-tools | DEBUG   | findingSearch0  | WriteQueue <queue.Queue object at 0x7fc3b41fef28> task services put
2022-10-31 08:08:18,846 | sonar-tools | INFO    | MainThread      | Starting finding writer thread 'findingWriter'
2022-10-31 08:08:18,847 | sonar-tools | INFO    | findingSearch0  | Project 'services' issue search
2022-10-31 08:08:18,847 | sonar-tools | DEBUG   | findingSearch0  | GET: squ_ca***08@https://sonarhost.biz/api/server/version
2022-10-31 08:08:18,870 | sonar-tools | DEBUG   | findingSearch0  | GET: squ_ca***08@https://sonarhost.biz/api/system/info



I tried to even check if we are getting the data with Admin user https://sonarhost.biz/api/system/info, it is working.  Please help me out on this. 

Thanks,
Prasad.

**Comment by okorach** [comment]
Hello @prasad-clouduser,

OK, I think I get it. The response of api/system/info has changed with version 9.7.
I should be able to adjust quickly.

**Comment by okorach** [comment]
See #861

**Comment by prasad-clouduser** [comment]
Hi @okorach 

Thanks for your reply. but when will it be released?. I have the latest version of SonarQube 9.7 only in my dev environment. 

Thanks,
Prasad.

**Comment by okorach** [comment]
I will release today. This may impact a ton of users.
For the record, the problem does not come from `sonar-tools` but from a backward compatibility breaking change introduced in SonarQUbe 9.7

**Comment by okorach** [comment]
@prasad-clouduser I just released https://github.com/okorach/sonar-tools/releases/tag/v2.6 that should fix your problem
Please confirm if everything is OK or not

**Comment by prasad-clouduser** [comment]
@okorach thats too quick :) Its working now. I have one more question, after scanning this binary if we find any CVEs will you be able to resolve them? like any critical or high vuls.

**Comment by okorach** [comment]
@prasad-clouduser 
Well I cannot commit to this without knowing what kind of scans you may run and problems you may find.
But generally speaking I will try to keep it as CVE free as possible.
For instance, if you scan is only on dependencies (SCA type of scan) I commit to update dependencies to eliminate the CVE.
