### ISSUE TITLE
Copied from issue #863

### ISSUE THREAD

**Issue by smclinden** [okorach/sonar-tools#866]
I'm getting conflicting messages. I have all the privileges that you require (full Administrative access) but it is looking for a User token (squ) yet I get:

```
2023-01-15 11:42:54,913 | sonar-tools | CRITICAL | ProjectAudit6   | For request URL https://sonartest.xxx.com/ap
i/ce/activity?status=SUCCESS%2CPENDING%2CIN_PROGRESS%2CFAILED%2CCANCELED&additionalFields=warnings&onlyCurrents=true&com
ponent=boot-loops-react-native
HTTP error 403 - Insufficient permissions to perform operation: Insufficient privileges
```
Suggestions?

_Originally posted by @smclinden in https://github.com/okorach/sonar-tools/issues/863#issuecomment-1383199925_

**Comment by smclinden** [comment]
Also, the --file and --format arguments to sonar-audit don't appear to have any effect. The output is being directed to stdout no matter what.

**Comment by okorach** [comment]
Hello @smclinden,

> I'm getting conflicting messages. I have all the privileges that you require (full Administrative access) but it is looking for a User token (squ)

Thanks for the information. This helps to understand the potential problem.
Though the tool only reflects the error coming from SonarQube. It seems that a you need a squ_ token from a superadmin user.
Can you try a curl with the same API request and check if your token allows for the API call.

curl -X GET - <YOUR_TOKEN>: "https://sonartest.xxx.com/ap
i/ce/activity?status=SUCCESS%2CPENDING%2CIN_PROGRESS%2CFAILED%2CCANCELED&additionalFields=warnings&onlyCurrents=true&component=boot-loops-react-native"

If you get teh same error it means that you token is not suitable. Try logging as the super admin and create a user token.

I'll check for the --file and --format. Can you you confirm that you're using the latest version of sonar-tools ?

**Comment by okorach** [comment]
Hi @smclinden,
1. Did you try to run the curl command alone to see if the problem had anything to do with sonar-tools or it's a SonarQube permission problem that would happen with any client?
2. Did you try with a squ_token, not a sqa_token? What is the outcome?
Best

**Comment by okorach** [comment]
Hi @smclinden, in the absence of feedback I will close this issue as incomplete.
If you still face the problem feel free to reopen with the information requested above.
Note that I will release soon sonar-tools v2.7.1 that includes several fixes
