### ISSUE TITLE
Support csv export for sonar-housekeeper tool

### ISSUE THREAD

**Issue by VijaySHegde** [okorach/sonar-tools#873]
As I can see https://github.com/okorach/sonar-tools#sonar-housekeeper
`sonar-housekeeper [-P <days>] [-B <days>] [-R <days>] [-T <days>] [--mode delete] [-h]`

The sonar-housekeeper tool doesn't provide a option to generate a file out of it, it would be really helpful if this works similar to other tools such as sonar-loc and sonar-audit which support exporting into a _csv_ file.

cc: @okorach @versat

**Comment by okorach** [comment]
I see your point @VijaySHegde, but Sonar Housekeeper:
- Only checks for items that require housekeeping (ie items that are fine are not listed)
- Produce information that pertains to different objects (projects, branches, PRs, tokens)

`sonar-loc` already produces the projects last analysis date for projects so I don't think you need anything for projects
`sonar-measures-export` should allow you to export branches last analysis date so, same here, I don't think you need anything

Remains the question of having a CSV report of tokens, with users, token type and expiration date (if any). Is that what you need? Can you clarify a bit?

**Comment by VijaySHegde** [comment]
@okorach Thanks for clarifying that, I wasn’t considering `sonar-measures-export` before raising the issue. I think I'm good with the AS-IS state now.

Thanks a ton for the wonderful and very useful tool, much appreciated.

**Comment by okorach** [comment]
OK, closing then. 👍
