### ISSUE TITLE
Using sonar-findings-export tool without 'Administer System' permission

### ISSUE THREAD

**Issue by abi55** [okorach/sonar-tools#908]
sonar-findings-export tool tries to use '/api/projects/search' which needs 'Administer System' permission. But we can access all issues for a project with 'api/issues/search' api with only 'Browse' permission on the specified project(s). 
Can you please update sonar-findings-export tool to work with out 'Administer System' permission?

**Comment by okorach** [comment]
Hello @abi55,
You're right, but actually `sonar-findings-export` can be used in 2 ways: with or without a list of project keys.
When you don't provide any project keys `sonar-findings-export` reads first the list of projects from the platform to then search for their findings.
When you do provide the project key(s) his step is not needed, and that's right that the tool needlessly call `/api/projects/search`
I will make that improvement (but note that this will no longer needed Admin System permission ONLY if you provide one or several project keys on the command line.

**Comment by okorach** [comment]
Hello @abi55,

Sorry for the delay in tackling this. I have been very busy with my main job lately.
Please find attached a pre-version that should fix your problem. Can you verify if that works in your environment. If so, I will make an official release.
To install simply download and uzip the attached and run: `pip install sonar_tools-2.8-py3-none-any.whl`

[sonar_tools-2.8-py3-none-any.whl.zip](https://github.com/okorach/sonar-tools/files/13063147/sonar_tools-2.8-py3-none-any.whl.zip)

Best, Olivier

**Comment by abi55** [comment]
Hi @okorach,

Yes, it is working as expected. Thank you for your support.

Regards,
Abinash
