### ISSUE TITLE
self signed ssl error

### ISSUE THREAD

**Issue by sg0133** [okorach/sonar-tools#931]
If there is any parameter i can pass to ignore ssl verification.
`sonar-audit -u <URL> -t <token> -w settings `
It will be helpful if i can pass some parameter to ignore ssl verification.

**Comment by okorach** [comment]
Hello @sg0133 ,
Your post lacks enough information.
Can you explain:
- Your SonarQube setup (HTTP, HTTPS, etc...)
- The command you run (please run in DEBUG and attach the logs, that you can redact if needed)
- The error your get
Thanks

**Comment by okorach** [comment]
Following up on this @sg0133 . Can you provide more context ? See questions above. Thank you

**Comment by okorach** [comment]
Last call @sg0133. Can you provide more context? If I don't have enough details on the problem, I can't fix it and therefore I will close the issue as won't fix

**Comment by okorach** [comment]
In the absence of further feedback I am closing this as Won't fix
