### ISSUE TITLE
Defaults not applied for Quality Gates, Quality Profiles

### ISSUE THREAD

**Issue by dhutchison** [okorach/sonar-tools#932]
Hi, 

First off this looks like a really useful tool, and plugs a bit of a gap with doing Configuration as Code in Sonarqube - thanks!

From a quick initial skim however it looks like there is an issue where defaults are not set for quality gates & profiles - is this a known gap or is there something I am missing?

I was following some examples to perform an export then re-import using:
```
sonar-config -t <token) --export --what "qualitygates,qualityprofiles,users,groups" -f partial_export.json
```

I can see in the generated json file that it knows about the defaults, e.g. 

```
"java": {
         "Sonar way": {
            "children": {
               "MyJavaProfile": {
                  "isDefault": true,
                  "rules": {
                     "java:S1194": "MAJOR",
                     "java:S2308": "MAJOR"
                  }
               }
            },
            "isBuiltIn": true
         }
      }
```

However the default is not set after I delete & re-import the quality profile.

**Comment by okorach** [comment]
Hello @dhutchison ,

Thanks for the encouragements and thanks for reporting this.
I indeed confirm the problem and I will fix that in a soon to come release (2.8.2 probably)
