### ISSUE TITLE
HTTPSConnectionPool Read Timed out

### ISSUE THREAD

**Issue by k0mand1r** [okorach/sonar-tools#990]
SonarQube CE Version: 10.1.0.73491
Sonar-tools version: 2.9
Reverse proxy: nginx

Last week this worked perfectly so I think something changed on our side on something out of my span of control. Would be easily solvable if I can adjust the timeout in the script.

command: 
sonar-housekeeper -t $SONAR_TOKEN -u $SONAR_HOST_URL -v DEBUG -P 180 --mode dry-run

output:
sonar-tools | CRITICAL | MainThread | HTTPSConnectionPool(host='HOST', port=443): Read timed out. (read timeout=10)
FATAL: HTTPSConnectionPool(host='HOST', port=443): Read timed out. (read timeout=10)

logs:
sonar access log: 
<IP> - - [02/Apr/2024:15:11:43 +0200] "GET /api/projects/search?qualifiers=TRK&ps=500&p=1 HTTP/1.1" 200 - "-" "<USER AGENT>" "AY6ez00Srnqv4NhhAABa"
nginx access log: <IP> - <TOKEN> [02/Apr/2024:15:20:29 +0200] "GET /api/projects/search?qualifiers=TRK&ps=500&p=1 HTTP/1.1" **499** 0 "-" "sonar-tools 2.9"

Status code 499 is thrown with a client aborted the request.

I've already increased the timeout values on nginx side, but the read timeout in the message stays at 10s. 

Is this something set by default in sonar-housekeeper and other sonar-tools? Are we able to adjust the timeout in the different sonar-tools?

EDIT: I saw the following change from 3 weeks ago: 
timeout on requests #962

**Comment by okorach** [comment]
Hello @k0mand1r,

Indeed the timeout is currently hardcoded to 10s in sonar-tools, it was deemed sufficient for any SonarQube HTTP request but apparently it may not be. I'll see if I can make that configurable in an easy way.

**Comment by k0mand1r** [comment]
Thanks for your time and effort you put into the sonar-tools project :)

**Comment by okorach** [comment]
Hello @k0mand1r,

I added the `--httpTimeout` option to all sonar-tools CLI tools (Default 10s if not specified).
That should allow you to adjust the value that works for you.

I attach a preview of sonar-tools 2.10. 
[sonar_tools-2.10-py3-none-any.whl.zip](https://github.com/okorach/sonar-tools/files/14907139/sonar_tools-2.10-py3-none-any.whl.zip)
Install with:
```
unzip sonar_tools-2.10-py3-none-any.whl.zip
pip uninstall sonar-tools
pip install sonar_tools-2.10-py3-none-any.whl
```
Let me know if that helps
